package template

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/backforge/deployment/internal/state"
)

// BuildContext is a temporary directory containing Dockerfile and server.go
// ready to pass to `docker build`.
type BuildContext struct {
	Dir string // path to the temp dir (caller must defer os.RemoveAll)
}

// GenerateData carries all values interpolated into the templates.
type GenerateData struct {
	ProjectName string
	Target      string
	Port        int
	Tables      []string
	GeneratedAt string
}

var dockerfileTemplate = template.Must(template.New("dockerfile").Parse(`# Generated by BackForge Deployment Engine
# Project: {{ .ProjectName }}
# Target:  {{ .Target }}
# Generated: {{ .GeneratedAt }}

FROM golang:1.24-alpine AS builder
WORKDIR /build
COPY server.go .
RUN go mod init backforge-runtime && go build -o runtime server.go

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /build/runtime .
COPY project_state.json .
EXPOSE {{ .Port }}
ENV BACKFORGE_PORT={{ .Port }}
ENV BACKFORGE_PROJECT={{ .ProjectName }}
LABEL org.backforge.project="{{ .ProjectName }}"
LABEL org.backforge.target="{{ .Target }}"
CMD ["./runtime"]
`))

// serverGoSource is the embedded runtime – a minimal HTTP server that reads
// project_state.json and serves /health and per-table /api/{table} routes.
const serverGoSource = `package main

import (
	"encoding/json"
	"log"
	"net/http"
	"os"
)

type projectState struct {
	Meta   map[string]interface{} ` + "`json:\"meta\"`" + `
	Schema struct {
		Tables []struct {
			Name string ` + "`json:\"name\"`" + `
		} ` + "`json:\"tables\"`" + `
	} ` + "`json:\"schema\"`" + `
}

func main() {
	port := os.Getenv("BACKFORGE_PORT")
	if port == "" {
		port = "3000"
	}

	raw, err := os.ReadFile("project_state.json")
	if err != nil {
		log.Fatalf("cannot read project_state.json: %v", err)
	}
	var s projectState
	if err := json.Unmarshal(raw, &s); err != nil {
		log.Fatalf("cannot parse project_state.json: %v", err)
	}

	projectName, _ := s.Meta["name"].(string)

	mux := http.NewServeMux()
	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]string{"status": "ok", "project": projectName})
	})
	mux.HandleFunc("/state", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write(raw)
	})
	for _, t := range s.Schema.Tables {
		name := t.Name
		mux.HandleFunc("/api/"+name, func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			json.NewEncoder(w).Encode([]interface{}{})
		})
	}

	log.Printf("BackForge runtime listening on :%s (project: %s)", port, projectName)
	log.Fatal(http.ListenAndServe(":"+port, mux))
}
`

// GenerateBuildContext creates a temp directory with Dockerfile + server.go
// populated from the given ProjectState.
func GenerateBuildContext(ps *state.ProjectState, projectStateJSON []byte, target string, port int) (*BuildContext, error) {
	dir, err := os.MkdirTemp("", "backforge-build-*")
	if err != nil {
		return nil, fmt.Errorf("create temp dir: %w", err)
	}

	tables := make([]string, len(ps.Schema.Tables))
	for i, t := range ps.Schema.Tables {
		tables[i] = t.Name
	}

	data := GenerateData{
		ProjectName: ps.Meta.Name,
		Target:      target,
		Port:        port,
		Tables:      tables,
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
	}

	// Write Dockerfile
	df, err := os.Create(filepath.Join(dir, "Dockerfile"))
	if err != nil {
		os.RemoveAll(dir)
		return nil, fmt.Errorf("create Dockerfile: %w", err)
	}
	if err := dockerfileTemplate.Execute(df, data); err != nil {
		df.Close()
		os.RemoveAll(dir)
		return nil, fmt.Errorf("render Dockerfile: %w", err)
	}
	df.Close()

	// Write server.go
	if err := os.WriteFile(filepath.Join(dir, "server.go"), []byte(serverGoSource), 0644); err != nil {
		os.RemoveAll(dir)
		return nil, fmt.Errorf("write server.go: %w", err)
	}

	// Copy project_state.json
	if err := os.WriteFile(filepath.Join(dir, "project_state.json"), projectStateJSON, 0644); err != nil {
		os.RemoveAll(dir)
		return nil, fmt.Errorf("write project_state.json: %w", err)
	}

	return &BuildContext{Dir: dir}, nil
}

// RenderDockerfile renders only the Dockerfile content to a string (for previews).
func RenderDockerfile(projectName, target string, port int) (string, error) {
	data := GenerateData{
		ProjectName: projectName,
		Target:      target,
		Port:        port,
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
	}
	var sb strings.Builder
	if err := dockerfileTemplate.Execute(&sb, data); err != nil {
		return "", err
	}
	return sb.String(), nil
}
