package generators

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/backforge/code-generator/internal/schema"
)

// GenerateHandlers generates Go CRUD handler files (one per table) using net/http + chi.
// Returns map of filename → Go source.
func GenerateHandlers(state *schema.ProjectState) map[string]string {
	files := make(map[string]string)
	for _, table := range state.Schema.Tables {
		filename := fmt.Sprintf("%s_handler.go", table.Name)
		files[filename] = generateTableHandler(table)
	}
	return files
}

func generateTableHandler(t schema.Table) string {
	typeName := toPascalCase(t.Name)
	singular := toSingular(typeName)
	varName := toLowerFirst(singular)
	pkField := primaryKeyField(t)

	var sb strings.Builder

	sb.WriteString(fmt.Sprintf(`// Code generated by BackForge Code Generator. DO NOT EDIT.
package handlers

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
)

// %s represents a row in the %s table.
type %s struct {
`, singular, t.Name, singular))

	for _, f := range t.Fields {
		goType := fieldTypeToGo(f.FieldType, f.Nullable)
		jsonTag := f.Name
		sb.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", toPascalCase(f.Name), goType, jsonTag))
	}
	sb.WriteString("}\n\n")

	// List handler
	sb.WriteString(fmt.Sprintf(`// List%s handles GET /%s
func List%s(w http.ResponseWriter, r *http.Request) {
	// TODO: query SELECT * FROM %s
	writeJSON(w, http.StatusOK, []%s{})
}

`, typeName, t.Name, typeName, t.Name, singular))

	// Get handler
	pkParam := "id"
	if pkField != nil {
		pkParam = pkField.Name
	}
	sb.WriteString(fmt.Sprintf(`// Get%s handles GET /%s/{%s}
func Get%s(w http.ResponseWriter, r *http.Request) {
	%s := chi.URLParam(r, "%s")
	if %s == "" {
		http.Error(w, "%s required", http.StatusBadRequest)
		return
	}
	// TODO: SELECT * FROM %s WHERE %s = $1
	writeJSON(w, http.StatusOK, map[string]string{"%s": %s})
}

`, typeName, t.Name, pkParam,
		typeName,
		pkParam, pkParam,
		pkParam, pkParam,
		t.Name, pkParam,
		pkParam, pkParam))

	// Create handler
	sb.WriteString(fmt.Sprintf(`// Create%s handles POST /%s
func Create%s(w http.ResponseWriter, r *http.Request) {
	var %s %s
	if err := json.NewDecoder(r.Body).Decode(&%s); err != nil {
		http.Error(w, "invalid JSON: "+err.Error(), http.StatusBadRequest)
		return
	}
	// TODO: INSERT INTO %s ...
	writeJSON(w, http.StatusCreated, %s)
}

`, typeName, t.Name,
		typeName,
		varName, singular,
		varName,
		t.Name,
		varName))

	// Update handler
	sb.WriteString(fmt.Sprintf(`// Update%s handles PUT /%s/{%s}
func Update%s(w http.ResponseWriter, r *http.Request) {
	%s := chi.URLParam(r, "%s")
	if %s == "" {
		http.Error(w, "%s required", http.StatusBadRequest)
		return
	}
	var %s %s
	if err := json.NewDecoder(r.Body).Decode(&%s); err != nil {
		http.Error(w, "invalid JSON: "+err.Error(), http.StatusBadRequest)
		return
	}
	// TODO: UPDATE %s SET ... WHERE %s = $1
	_ = %s
	writeJSON(w, http.StatusOK, %s)
}

`, typeName, t.Name, pkParam,
		typeName,
		pkParam, pkParam,
		pkParam, pkParam,
		varName, singular,
		varName,
		t.Name, pkParam,
		pkParam,
		varName))

	// Delete handler
	sb.WriteString(fmt.Sprintf(`// Delete%s handles DELETE /%s/{%s}
func Delete%s(w http.ResponseWriter, r *http.Request) {
	%s := chi.URLParam(r, "%s")
	if %s == "" {
		http.Error(w, "%s required", http.StatusBadRequest)
		return
	}
	// TODO: DELETE FROM %s WHERE %s = $1
	w.WriteHeader(http.StatusNoContent)
}
`, typeName, t.Name, pkParam,
		typeName,
		pkParam, pkParam,
		pkParam, pkParam,
		t.Name, pkParam))

	return sb.String()
}

// GenerateRouter generates a Go router file that registers all table routes.
func GenerateRouter(state *schema.ProjectState) string {
	var sb strings.Builder
	sb.WriteString(`// Code generated by BackForge Code Generator. DO NOT EDIT.
package handlers

import "github.com/go-chi/chi/v5"

func NewRouter() *chi.Mux {
	r := chi.NewRouter()
`)
	for _, t := range state.Schema.Tables {
		typeName := toPascalCase(t.Name)
		pkField := primaryKeyField(t)
		pkParam := "id"
		if pkField != nil {
			pkParam = pkField.Name
		}
		sb.WriteString(fmt.Sprintf(`
	r.Get("/%s", List%s)
	r.Post("/%s", Create%s)
	r.Get("/%s/{%s}", Get%s)
	r.Put("/%s/{%s}", Update%s)
	r.Delete("/%s/{%s}", Delete%s)
`, t.Name, typeName,
			t.Name, typeName,
			t.Name, pkParam, typeName,
			t.Name, pkParam, typeName,
			t.Name, pkParam, typeName))
	}
	sb.WriteString(`
	return r
}

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}
`)
	// Add json import if needed
	result := sb.String()
	if strings.Contains(result, "json.NewEncoder") {
		result = strings.Replace(result,
			`import "github.com/go-chi/chi/v5"`,
			"import (\n\t\"encoding/json\"\n\n\t\"github.com/go-chi/chi/v5\"\n)", 1)
	}
	return result
}

// --- helpers ---

func primaryKeyField(t schema.Table) *schema.Field {
	for _, f := range t.Fields {
		if f.PrimaryKey {
			return &f
		}
	}
	return nil
}

func fieldTypeToGo(ft schema.FieldType, nullable bool) string {
	var base string
	switch ft {
	case schema.FieldTypeText:
		base = "string"
	case schema.FieldTypeInteger:
		base = "int32"
	case schema.FieldTypeBigInt:
		base = "int64"
	case schema.FieldTypeFloat:
		base = "float64"
	case schema.FieldTypeBoolean:
		base = "bool"
	case schema.FieldTypeUUID:
		base = "string"
	case schema.FieldTypeTimestamp:
		base = "string" // ISO 8601 string; use time.Time in real codegen
	case schema.FieldTypeJSON:
		base = "any"
	case schema.FieldTypeBytes:
		base = "[]byte"
	default:
		base = "string"
	}
	if nullable {
		switch base {
		case "string":
			return "*string"
		case "int32":
			return "*int32"
		case "int64":
			return "*int64"
		case "float64":
			return "*float64"
		case "bool":
			return "*bool"
		case "any":
			return "any"
		}
	}
	return base
}

func toPascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-' || r == ' '
	})
	var out strings.Builder
	for _, p := range parts {
		if len(p) > 0 {
			out.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	return out.String()
}

func toLowerFirst(s string) string {
	if s == "" {
		return s
	}
	runes := []rune(s)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

// toSingular removes trailing 's' for a simple singular form.
// e.g. "Users" → "User", "Posts" → "Post"
func toSingular(s string) string {
	if strings.HasSuffix(s, "ies") {
		return s[:len(s)-3] + "y"
	}
	if strings.HasSuffix(s, "s") && len(s) > 1 {
		return s[:len(s)-1]
	}
	return s
}
