package generators

import (
	"fmt"
	"strings"

	"github.com/backforge/code-generator/internal/schema"
)

// GenerateGitHubOAuth generates a self-contained GitHub OAuth handler file for the
// generated project. The client_id and callback_url are pre-filled from the stored
// BackForge credentials (non-secret). The client_secret must be supplied at runtime
// via the GITHUB_CLIENT_SECRET environment variable — it is never hardcoded.
//
// Routes to register in the generated router:
//
//	r.Get("/auth/github",          handlers.GitHubAuthorize)
//	r.Get("/auth/github/callback", handlers.GitHubCallback)
func GenerateGitHubOAuth(cfg *schema.GitHubOAuthConfig) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(`// Code generated by BackForge Code Generator. DO NOT EDIT.
// GitHub OAuth 2.0 handler — reads credentials from environment variables.
// Pre-filled defaults come from your BackForge project config (non-secret only).
package handlers

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"strings"
)

func ghEnv(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

// GitHub OAuth credentials — override via environment variables.
var (
	ghClientID     = ghEnv("GITHUB_CLIENT_ID", %q)
	ghCallbackURL  = ghEnv("GITHUB_CALLBACK_URL", %q)
	ghClientSecret = os.Getenv("GITHUB_CLIENT_SECRET") // must be set; never hardcoded
)

// GitHubAuthorize redirects the user to the GitHub OAuth consent page.
// GET /auth/github
func GitHubAuthorize(w http.ResponseWriter, r *http.Request) {
	if ghClientSecret == "" {
		http.Error(w, "GitHub OAuth not configured: GITHUB_CLIENT_SECRET is not set", http.StatusServiceUnavailable)
		return
	}
	state := ghRandomHex(16)
	// TODO: store state in session/redis for CSRF verification in GitHubCallback
	authURL := fmt.Sprintf(
		"https://github.com/login/oauth/authorize?client_id=%%s&redirect_uri=%%s&state=%%s&scope=user:email",
		url.QueryEscape(ghClientID),
		url.QueryEscape(ghCallbackURL),
		url.QueryEscape(state),
	)
	http.Redirect(w, r, authURL, http.StatusFound)
}

// GitHubCallback exchanges the OAuth code for an access token and fetches the user profile.
// GET /auth/github/callback
func GitHubCallback(w http.ResponseWriter, r *http.Request) {
	code := r.URL.Query().Get("code")
	if code == "" {
		http.Error(w, "missing code", http.StatusBadRequest)
		return
	}
	// TODO: verify state matches session to prevent CSRF

	ctx := r.Context()
	token, err := ghExchangeCode(ctx, code)
	if err != nil {
		http.Error(w, "OAuth exchange failed: "+err.Error(), http.StatusInternalServerError)
		return
	}

	profile, err := ghFetchProfile(ctx, token)
	if err != nil {
		http.Error(w, "failed to fetch GitHub profile: "+err.Error(), http.StatusInternalServerError)
		return
	}

	// TODO: upsert profile into your users table and issue a JWT
	ghWriteJSON(w, http.StatusOK, map[string]any{
		"github_id":    profile.ID,
		"login":        profile.Login,
		"email":        profile.Email,
		"access_token": token, // remove before production — store server-side only
	})
}

type ghUserProfile struct {
	ID    int64  `json:"id"`
	Login string `json:"login"`
	Email string `json:"email"`
}

func ghExchangeCode(ctx context.Context, code string) (string, error) {
	body := url.Values{
		"client_id":     {ghClientID},
		"client_secret": {ghClientSecret},
		"code":          {code},
		"redirect_uri":  {ghCallbackURL},
	}
	req, _ := http.NewRequestWithContext(ctx, http.MethodPost,
		"https://github.com/login/oauth/access_token",
		strings.NewReader(body.Encode()),
	)
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("Accept", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	var result struct {
		AccessToken string `json:"access_token"`
		Error       string `json:"error"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return "", fmt.Errorf("decode: %%w", err)
	}
	if result.Error != "" {
		return "", fmt.Errorf("github: %%s", result.Error)
	}
	return result.AccessToken, nil
}

func ghFetchProfile(ctx context.Context, token string) (ghUserProfile, error) {
	var p ghUserProfile
	req, _ := http.NewRequestWithContext(ctx, http.MethodGet, "https://api.github.com/user", nil)
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/vnd.github+json")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return p, err
	}
	defer resp.Body.Close()
	if err := json.NewDecoder(resp.Body).Decode(&p); err != nil {
		return p, err
	}
	return p, nil
}

func ghRandomHex(n int) string {
	b := make([]byte, n)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

func ghWriteJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

// GitHubOAuthEnvExample returns a .env.example snippet for GitHub OAuth setup.
func GitHubOAuthEnvExample() string {
	return fmt.Sprintf("# GitHub OAuth App credentials (https://github.com/settings/developers)\nGITHUB_CLIENT_ID=%s\nGITHUB_CLIENT_SECRET=<your-secret-here>\nGITHUB_CALLBACK_URL=%s\n",
		ghClientID, ghCallbackURL)
}
`, cfg.ClientID, cfg.CallbackURL))
	return sb.String()
}
