package generators

import (
"fmt"
"strings"

"github.com/backforge/code-generator/internal/schema"
)

// GenerateGitHubOAuth generates a self-contained GitHub OAuth handler file for the
// generated project. The client_id and callback_url are pre-filled from the stored
// BackForge credentials (non-secret). The client_secret must be supplied at runtime
// via the GITHUB_CLIENT_SECRET environment variable — it is never hardcoded.
//
// Routes to register in the generated router:
//
//r.Get("/auth/github",          handlers.GitHubAuthorize)
//r.Get("/auth/github/callback", handlers.GitHubCallback)
func GenerateGitHubOAuth(cfg *schema.GitHubOAuthConfig) string {
clientID := cfg.ClientID
callbackURL := cfg.CallbackURL

var sb strings.Builder
sb.WriteString("// Code generated by BackForge Code Generator. DO NOT EDIT.\n")
sb.WriteString("// GitHub OAuth 2.0 handler — reads credentials from environment variables.\n")
sb.WriteString("package handlers\n\n")
sb.WriteString("import (\n\t\"context\"\n\t\"crypto/rand\"\n\t\"encoding/hex\"\n")
sb.WriteString("\t\"encoding/json\"\n\t\"fmt\"\n\t\"net/http\"\n\t\"net/url\"\n\t\"os\"\n\t\"strings\"\n)\n\n")

sb.WriteString("func ghEnv(key, fallback string) string {\n")
sb.WriteString("\tif v := os.Getenv(key); v != \"\" { return v }\n")
sb.WriteString("\treturn fallback\n}\n\n")

sb.WriteString(fmt.Sprintf("var (\n\tghClientID     = ghEnv(\"GITHUB_CLIENT_ID\", %q)\n\tghCallbackURL  = ghEnv(\"GITHUB_CALLBACK_URL\", %q)\n\tghClientSecret = os.Getenv(\"GITHUB_CLIENT_SECRET\")\n)\n\n",
clientID, callbackURL))

sb.WriteString("// GitHubAuthorize redirects the user to the GitHub OAuth consent page.\n// GET /auth/github\n")
sb.WriteString("func GitHubAuthorize(w http.ResponseWriter, r *http.Request) {\n")
sb.WriteString("\tif ghClientSecret == \"\" {\n\t\thttp.Error(w, \"GitHub OAuth not configured\", http.StatusServiceUnavailable)\n\t\treturn\n\t}\n")
sb.WriteString("\tstate := ghRandomHex(16)\n")
sb.WriteString("\tauthURL := fmt.Sprintf(\n\t\t\"https://github.com/login/oauth/authorize?client_id=%s&redirect_uri=%s&state=%s&scope=user:email\",\n")
sb.WriteString("\t\turl.QueryEscape(ghClientID), url.QueryEscape(ghCallbackURL), url.QueryEscape(state),\n\t)\n")
sb.WriteString("\thttp.Redirect(w, r, authURL, http.StatusFound)\n}\n\n")

sb.WriteString("// GitHubCallback handles the OAuth callback.\n// GET /auth/github/callback\n")
sb.WriteString("func GitHubCallback(w http.ResponseWriter, r *http.Request) {\n")
sb.WriteString("\tcode := r.URL.Query().Get(\"code\")\n\tif code == \"\" {\n\t\thttp.Error(w, \"missing code\", http.StatusBadRequest)\n\t\treturn\n\t}\n")
sb.WriteString("\tctx := r.Context()\n")
sb.WriteString("\ttoken, err := ghExchangeCode(ctx, code)\n\tif err != nil {\n\t\thttp.Error(w, \"OAuth exchange failed: \"+err.Error(), http.StatusInternalServerError)\n\t\treturn\n\t}\n")
sb.WriteString("\tprofile, err := ghFetchProfile(ctx, token)\n\tif err != nil {\n\t\thttp.Error(w, \"failed to fetch profile: \"+err.Error(), http.StatusInternalServerError)\n\t\treturn\n\t}\n")
sb.WriteString("\tghWriteJSON(w, http.StatusOK, map[string]any{\"github_id\": profile[\"id\"], \"login\": profile[\"login\"], \"email\": profile[\"email\"]})\n}\n\n")

sb.WriteString("func ghExchangeCode(ctx context.Context, code string) (string, error) {\n")
sb.WriteString("\tbody := url.Values{\"client_id\": {ghClientID}, \"client_secret\": {ghClientSecret}, \"code\": {code}, \"redirect_uri\": {ghCallbackURL}}\n")
sb.WriteString("\treq, _ := http.NewRequestWithContext(ctx, http.MethodPost, \"https://github.com/login/oauth/access_token\", strings.NewReader(body.Encode()))\n")
sb.WriteString("\treq.Header.Set(\"Content-Type\", \"application/x-www-form-urlencoded\")\n\treq.Header.Set(\"Accept\", \"application/json\")\n")
sb.WriteString("\tresp, err := http.DefaultClient.Do(req)\n\tif err != nil { return \"\", err }\n\tdefer resp.Body.Close()\n")
sb.WriteString("\tvar raw map[string]string\n")
sb.WriteString("\tif err := json.NewDecoder(resp.Body).Decode(&raw); err != nil { return \"\", fmt.Errorf(\"decode: %w\", err) }\n")
sb.WriteString("\tif errMsg := raw[\"error\"]; errMsg != \"\" { return \"\", fmt.Errorf(\"github error: %s\", errMsg) }\n")
sb.WriteString("\treturn raw[\"access_token\"], nil\n}\n\n")

sb.WriteString("func ghFetchProfile(ctx context.Context, token string) (map[string]any, error) {\n")
sb.WriteString("\treq, _ := http.NewRequestWithContext(ctx, http.MethodGet, \"https://api.github.com/user\", nil)\n")
sb.WriteString("\treq.Header.Set(\"Authorization\", \"Bearer \"+token)\n\treq.Header.Set(\"Accept\", \"application/vnd.github+json\")\n")
sb.WriteString("\tresp, err := http.DefaultClient.Do(req)\n\tif err != nil { return nil, err }\n\tdefer resp.Body.Close()\n")
sb.WriteString("\tvar profile map[string]any\n")
sb.WriteString("\tif err := json.NewDecoder(resp.Body).Decode(&profile); err != nil { return nil, err }\n")
sb.WriteString("\treturn profile, nil\n}\n\n")

sb.WriteString("func ghRandomHex(n int) string { b := make([]byte, n); _, _ = rand.Read(b); return hex.EncodeToString(b) }\n\n")
sb.WriteString("func ghWriteJSON(w http.ResponseWriter, status int, v any) {\n")
sb.WriteString("\tw.Header().Set(\"Content-Type\", \"application/json\"); w.WriteHeader(status); _ = json.NewEncoder(w).Encode(v)\n}\n")

return sb.String()
}