package generators

import (
	"fmt"
	"strings"

	"github.com/backforge/code-generator/internal/schema"
)

// GenerateQueries generates Go source files containing safe, parameterized SQL query
// constants for each table.  Using these constants prevents SQL injection because
// every variable value is passed as a positional argument ($1, $2 …) to the
// database driver — no string concatenation ever touches the query text.
//
// Returns map of filename → Go source.
func GenerateQueries(state *schema.ProjectState) map[string]string {
	files := make(map[string]string)
	for _, table := range state.Schema.Tables {
		filename := fmt.Sprintf("%s_queries.go", table.Name)
		files[filename] = generateTableQueries(table)
	}
	return files
}

func generateTableQueries(t schema.Table) string {
	typeName := toPascalCase(t.Name)

	pkField := primaryKeyField(t)
	pkName := "id"
	if pkField != nil {
		pkName = pkField.Name
	}

	// Non-PK, non-auto fields that appear in INSERT / UPDATE
	dataFields := dataOnlyFields(t, pkName)

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(
		"// Code generated by BackForge Code Generator. DO NOT EDIT.\n"+
			"// These constants contain ONLY parameterized queries ($1, $2, …).\n"+
			"// Never build SQL by string-formatting user input — use these constants instead.\n"+
			"package queries\n\n",
	))

	// ── SELECT ALL ────────────────────────────────────────────────────────────
	allCols := columnNames(t.Fields)
	sb.WriteString(fmt.Sprintf(
		"// SelectAll%s returns every row from %s.\n"+
			"// Usage:  rows, err := db.QueryContext(ctx, queries.SelectAll%s)\n"+
			"const SelectAll%s = `SELECT %s FROM %s`\n\n",
		typeName, t.Name,
		typeName,
		typeName, allCols, t.Name,
	))

	// ── SELECT BY PK ──────────────────────────────────────────────────────────
	sb.WriteString(fmt.Sprintf(
		"// Select%sByID returns the row matching %s = $1.\n"+
			"// Usage:  row := db.QueryRowContext(ctx, queries.Select%sByID, id)\n"+
			"const Select%sByID = `SELECT %s FROM %s WHERE %s = $1`\n\n",
		typeName, pkName,
		typeName,
		typeName, allCols, t.Name, pkName,
	))

	// ── INSERT ────────────────────────────────────────────────────────────────
	if len(dataFields) > 0 {
		insertCols, insertParams := buildInsertParts(dataFields)
		sb.WriteString(fmt.Sprintf(
			"// Insert%s inserts a new row and returns the generated primary key.\n"+
				"// Args: %s\n"+
				"// Usage:  err := db.QueryRowContext(ctx, queries.Insert%s, %s).Scan(&newID)\n"+
				"const Insert%s = `INSERT INTO %s (%s) VALUES (%s) RETURNING %s`\n\n",
			typeName, insertCols,
			typeName, insertCols,
			typeName, t.Name, insertCols, insertParams, pkName,
		))

		// ── UPDATE ────────────────────────────────────────────────────────────
		setClause, nextParam := buildSetClause(dataFields)
		sb.WriteString(fmt.Sprintf(
			"// Update%s updates all data columns for the row with %s = $%d.\n"+
				"// Args: %s, %s\n"+
				"// Usage:  _, err := db.ExecContext(ctx, queries.Update%s, %s, id)\n"+
				"const Update%s = `UPDATE %s SET %s WHERE %s = $%d`\n\n",
			typeName, pkName, nextParam,
			insertCols, pkName,
			typeName, insertCols+", id",
			typeName, t.Name, setClause, pkName, nextParam,
		))
	}

	// ── DELETE ────────────────────────────────────────────────────────────────
	sb.WriteString(fmt.Sprintf(
		"// Delete%s removes the row with %s = $1.\n"+
			"// Usage:  _, err := db.ExecContext(ctx, queries.Delete%s, id)\n"+
			"const Delete%s = `DELETE FROM %s WHERE %s = $1`\n",
		typeName, pkName,
		typeName,
		typeName, t.Name, pkName,
	))

	return sb.String()
}

// dataOnlyFields returns fields that should appear in INSERT/UPDATE
// (excludes the primary key so it is not double-counted).
func dataOnlyFields(t schema.Table, pkName string) []schema.Field {
	var result []schema.Field
	for _, f := range t.Fields {
		if f.Name != pkName {
			result = append(result, f)
		}
	}
	return result
}

// columnNames returns a comma-separated list of all field names.
func columnNames(fields []schema.Field) string {
	names := make([]string, len(fields))
	for i, f := range fields {
		names[i] = f.Name
	}
	return strings.Join(names, ", ")
}

// buildInsertParts returns (col_list, $1, $2, …) strings for INSERT.
func buildInsertParts(fields []schema.Field) (cols string, params string) {
	names := make([]string, len(fields))
	placeholders := make([]string, len(fields))
	for i, f := range fields {
		names[i] = f.Name
		placeholders[i] = fmt.Sprintf("$%d", i+1)
	}
	return strings.Join(names, ", "), strings.Join(placeholders, ", ")
}

// buildSetClause returns "col1 = $1, col2 = $2, …" and the next param index
// for use as the WHERE clause placeholder.
func buildSetClause(fields []schema.Field) (clause string, nextIndex int) {
	parts := make([]string, len(fields))
	for i, f := range fields {
		parts[i] = fmt.Sprintf("%s = $%d", f.Name, i+1)
	}
	return strings.Join(parts, ", "), len(fields) + 1
}
