// Package generators contains all code generation logic.
// Each generator takes a ProjectState and returns generated file contents as strings.
package generators

import (
	"fmt"
	"strings"

	"github.com/backforge/code-generator/internal/schema"
)

// GenerateSQL generates PostgreSQL DDL for all tables in the project schema.
// Returns a map of filename → SQL content.
func GenerateSQL(state *schema.ProjectState) map[string]string {
	files := make(map[string]string)
	for i, table := range state.Schema.Tables {
		filename := fmt.Sprintf("%03d_create_%s.sql", i+1, table.Name)
		files[filename] = generateTableDDL(table)
	}
	return files
}

func generateTableDDL(t schema.Table) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("-- Generated by BackForge Code Generator\n"))
	sb.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n", t.Name))

	cols := make([]string, 0, len(t.Fields))
	for _, f := range t.Fields {
		cols = append(cols, "    "+fieldToColumnDDL(f))
	}

	// Collect primary key fields
	var pkFields []string
	for _, f := range t.Fields {
		if f.PrimaryKey {
			pkFields = append(pkFields, f.Name)
		}
	}
	if len(pkFields) > 1 {
		// composite PK — add as table constraint
		cols = append(cols, fmt.Sprintf("    PRIMARY KEY (%s)", strings.Join(pkFields, ", ")))
	}

	sb.WriteString(strings.Join(cols, ",\n"))
	sb.WriteString("\n);\n")

	// Indexes
	for _, idx := range t.Indexes {
		unique := ""
		if idx.Unique {
			unique = "UNIQUE "
		}
		sb.WriteString(fmt.Sprintf("\nCREATE %sINDEX IF NOT EXISTS %s ON %s (%s);\n",
			unique, idx.Name, t.Name, strings.Join(idx.Fields, ", ")))
	}

	return sb.String()
}

func fieldToColumnDDL(f schema.Field) string {
	parts := []string{f.Name, fieldTypeToPG(f.FieldType)}

	if f.PrimaryKey && len(parts) > 0 {
		// PRIMARY KEY implies NOT NULL; mark inline only for single PK
		parts = append(parts, "PRIMARY KEY")
	} else {
		if !f.Nullable {
			parts = append(parts, "NOT NULL")
		}
		if f.Unique {
			parts = append(parts, "UNIQUE")
		}
	}

	if f.DefaultValue != nil {
		parts = append(parts, "DEFAULT "+*f.DefaultValue)
	}

	return strings.Join(parts, " ")
}

func fieldTypeToPG(ft schema.FieldType) string {
	switch ft {
	case schema.FieldTypeText:
		return "TEXT"
	case schema.FieldTypeInteger:
		return "INTEGER"
	case schema.FieldTypeBigInt:
		return "BIGINT"
	case schema.FieldTypeFloat:
		return "DOUBLE PRECISION"
	case schema.FieldTypeBoolean:
		return "BOOLEAN"
	case schema.FieldTypeUUID:
		return "UUID"
	case schema.FieldTypeTimestamp:
		return "TIMESTAMPTZ"
	case schema.FieldTypeJSON:
		return "JSONB"
	case schema.FieldTypeBytes:
		return "BYTEA"
	default:
		return "TEXT"
	}
}
